# build
FROM gradle:8.7-jdk21 AS build
WORKDIR /app
COPY . .
RUN gradle :arin-api:bootJar -x test

# run
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/arin-api/build/libs/app.jar app.jar
ENV TZ=Asia/Seoul
EXPOSE 8080
ENTRYPOINT ["java","-XX:+UseG1GC","-Duser.timezone=Asia/Seoul","-jar","/app/app.jar"]
