# 공통
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/arin
    username: arin
    password: arin0000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  redis:
    host: localhost   # ← 스프링이 호스트에서 돌 때
    port: 6379
    timeout: 2000

jwt:
  secret: "9Em2u5g21z17kI8gcJr7pahzcg5GTrn6IJXv4TnJJPM="
  is-base64: true
  issuer: arin
  audience: frontend
  expiration: 3600000          # 1h
  refresh-expiration: 604800000 # 7d

app:
  oauth2:
    redirect-uri: http://localhost:5173/oauth/success-popup
    allowed-origins:
      - http://localhost:5173
  security:
    refresh-cookie:
      name: refresh_token
      path: /api/auth/
      same-site: Lax
      secure: false
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
proxy:
  prefix: /api/proxy
  upstream: http://localhost:9000
  allowed-path-prefixes: /rag/
  connect-timeout-ms: 3000
  read-timeout-ms: 1200000
  forward-authorization: true
#  hmac:
#    secret: ""  # 필요 시 채워서 사용

--- # dev
spring:
  config:
    activate:
      on-profile: dev
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

--- # prod
spring:
  config:
    activate:
      on-profile: prod
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
app:
  security:
    refresh-cookie:
      secure: true
      same-site: None   # 크로스도메인이면 None + HTTPS 필수
