FROM pytorch/pytorch:2.2.2-cuda12.1-cudnn8-devel

COPY . /app
WORKDIR /app

# 시스템 패키지 업데이트 및 기본 도구 설치
RUN apt-get update && apt-get install -y \
    git curl wget unzip \
    && apt-get clean

# Python 패키지 설치
RUN pip install --no-cache-dir \
    sentence-transformers \
    faiss-gpu \
    transformers \
    accelerate \
    fastapi \
    uvicorn \
    httpx \
    tqdm \
    numpy \
    pandas
